language: node_js
node_js:
  - "stable"
cache: yarn
install:
  - yarn install
script:
  - yarn run test
deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master
